# # Install pre-commit hooks via
# pre-commit install

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.2.3
  hooks:
  - id: check-yaml

- repo: local
  hooks:
  - id: yapf
    name: yapf
    entry: yapf
    language: system
    types: [python]
    args: ["-i"]
