version: '2'

services:
  bokeh:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    volumes:
     - '/tmp:/app/.aiida/repository/curated-cofs'
    ports:
      - '5006:5006'
